-- Généré par seed_abacus_academy_sends.js — 2026-09-02T21:53:11.537Z
-- 122 destinataires, statut 'a_envoyer'.
-- Idempotent-friendly : lancer une seule fois (pas de contrainte d'unicité).

INSERT INTO ref.abacus_academy_sends
  (structure, email, type, pays, dirigeant, statut)
VALUES
  ('ISM — Institut Supérieur de Management', 'info@ism.edu.sn', 'universite', 'Sénégal', 'Amadou Diaw', 'a_envoyer'),
  ('Groupe Sup de Co Dakar', 'admission@supdeco.edu.sn', 'universite', 'Sénégal', 'Abdoul Aziz Sy Junior', 'a_envoyer'),
  ('IAM Dakar — Institut Africain de Management', 'info@groupeiam.com', 'universite', 'Sénégal', 'Bamba Fall', 'a_envoyer'),
  ('Université Amadou Hampâté Bâ (UAHB)', 'contact@uahb.sn', 'universite', 'Sénégal', 'Michel Claver Gbaya', 'a_envoyer'),
  ('Université Dakar Bourguiba (UDB)', 'info@udb-sn.com', 'universite', 'Sénégal', 'Pr Sakhir Thiam', 'a_envoyer'),
  ('Université du Sahel (UNIS)', 'contact@sahel.education', 'universite', 'Sénégal', 'Pr El Hadji Issa Sall', 'a_envoyer'),
  ('AFI — L''Université de l''Entreprise', 'afi@afi-ue.sn', 'universite', 'Sénégal', 'Sophie Coulibaly Diouf', 'a_envoyer'),
  ('UCAO / Complexe Saint-Michel (Dakar)', 'stmichel@ucao.edu.sn', 'universite', 'Sénégal', 'Dr Yacente Diène Dione', 'a_envoyer'),
  ('Groupe ISI — Institut Supérieur d''Informatique', 'contact@groupeisi.com', 'universite', 'Sénégal', 'Abdou Sambe', 'a_envoyer'),
  ('UN-CHK — Université numérique Cheikh Hamidou Kane', 'contact@unchk.edu.sn', 'universite', 'Sénégal', 'Pr Samuel Ouya', 'a_envoyer'),
  ('PIGIER Côte d''Ivoire', 'pigierci@pigierci.com', 'universite', 'Côte d''Ivoire', 'Jérémie Alfred N''Gouan', 'a_envoyer'),
  ('CERAP / Université Jésuite d''Abidjan', 'secretariat.universitaire@cerap-inades.org', 'universite', 'Côte d''Ivoire', 'Père Arsène Brice Bado, sj', 'a_envoyer'),
  ('Institut Universitaire d''Abidjan (IUA)', 'info@iua.org', 'universite', 'Côte d''Ivoire', 'Pr Aka Kouamé', 'a_envoyer'),
  ('Groupe HETEC', 'info@groupehetec.com', 'universite', 'Côte d''Ivoire', 'Parfait Seri', 'a_envoyer'),
  ('ESCA — Groupe ESCA Côte d''Ivoire (privé)', 'labelesca40@gmail.com', 'universite', 'Côte d''Ivoire', 'Pr Abdoulaye Ouattara', 'a_envoyer'),
  ('UCAO-UUA (Abidjan)', 'info@ucaouua.com', 'universite', 'Côte d''Ivoire', 'Père Vivien Somda', 'a_envoyer'),
  ('Groupe CSI Pôle Polytechnique', 'info@groupecsi-pp.com', 'universite', 'Côte d''Ivoire', 'Raoul Aby', 'a_envoyer'),
  ('UST-CI — Université des Sciences et Technologies de Côte d''Ivoire', 'rusta.ustci@gmail.com', 'universite', 'Côte d''Ivoire', 'Pr François N''Guessan Kouakou', 'a_envoyer'),
  ('AGITEL Formation', 'infos@agitel-formation.net', 'universite', 'Côte d''Ivoire', 'Bamba Sory', 'a_envoyer'),
  ('Groupe LOKO', 'infos@groupeloko.com', 'universite', 'Côte d''Ivoire', '', 'a_envoyer'),
  ('IHEM — Institut des Hautes Études en Management', 'contact@ihemmali.com', 'universite', 'Mali', 'Abdallah Coulibaly', 'a_envoyer'),
  ('ESGIC — École Supérieure de Gestion, Informatique et Comptabilité', 'contact@esgicbamako.com', 'universite', 'Mali', 'Diakaridia Camara', 'a_envoyer'),
  ('USLB — Université Scientifique Libre de Bamako', 'contact@uslb-edu.com', 'universite', 'Mali', 'Dr Mohamed Ag Baraika', 'a_envoyer'),
  ('Université Mary Saint Claire', 'info@univmarysaintclaire.com', 'universite', 'Mali', 'Cheickna Hamala Bathily', 'a_envoyer'),
  ('IIM Bamako — Institut International de Management', 'info@iimuniversitebamako.com', 'universite', 'Mali', '', 'a_envoyer'),
  ('IAM Bamako — Institut Africain de Management', 'iambamako@groupeiam.com', 'universite', 'Mali', 'Seynabou Diallo', 'a_envoyer'),
  ('ISPRIC', 'ispric@ispric.com', 'universite', 'Mali', 'Dr Mohamed Gakou', 'a_envoyer'),
  ('UIE — Université Internationale (Privée) d''Excellence', 'contact@uiemali.ml', 'universite', 'Mali', 'Moussa Timbine', 'a_envoyer'),
  ('ISIM — Institut Supérieur d''Informatique et de Management', 'etudes@isim-school.com', 'universite', 'Mali', '', 'a_envoyer'),
  ('ESCT — École Supérieure de Commerce et de Technologie', 'infos@esct.ml', 'universite', 'Mali', '', 'a_envoyer'),
  ('Université Aube Nouvelle (U-AUBEN)', 'info@u-auben.com', 'universite', 'Burkina Faso', 'Isidore Gnatan Kini', 'a_envoyer'),
  ('Université Saint Thomas d''Aquin (USTA)', 'info@usta.bf', 'universite', 'Burkina Faso', 'Pr Innocent Pierre Guissou', 'a_envoyer'),
  ('Université Libre du Burkina (ULB)', 'info@ulburkina.org', 'universite', 'Burkina Faso', 'Karim Ouédraogo', 'a_envoyer'),
  ('Université de l''Unité Africaine (UUA, ex-IAM Ouaga)', 'iam@iamburkina.com', 'universite', 'Burkina Faso', 'Dr Amed Moussa Diallo', 'a_envoyer'),
  ('ISGE-BF — Institut Supérieur de Génie Électrique', 'isge-bf@isge-bf.org', 'universite', 'Burkina Faso', 'Innocent Compaoré', 'a_envoyer'),
  ('IIM Ouaga — Institut International de Management', 'contact@iimburkina.com', 'universite', 'Burkina Faso', 'Dr Méwinesso Tchanadema', 'a_envoyer'),
  ('ISPP — Institut Supérieur Privé Polytechnique', 'info@ispp.bf', 'universite', 'Burkina Faso', 'Sabine Marie Clémentine Yaméogo/Nikièma', 'a_envoyer'),
  ('ESCO-IGES', 'contact@esco-iges.com', 'universite', 'Burkina Faso', 'Dr Désiré Nakoulma', 'a_envoyer'),
  ('ESC Ouaga — École Supérieure de Commerce', 'info@esc-ouaga.com', 'universite', 'Burkina Faso', '', 'a_envoyer'),
  ('CERPAMAD', 'info@cerpamad.com', 'universite', 'Burkina Faso', 'Moumouni Séré', 'a_envoyer'),
  ('Sup''Management Burkina', 'supmgtburkina@supmanagement.bf', 'universite', 'Burkina Faso', 'Dr Alassane Nikiéma', 'a_envoyer'),
  ('ESPA-MT', 'info@espa-mt.com', 'universite', 'Niger', 'Ousmane Ali Salé', 'a_envoyer'),
  ('École Polytechnique de Niamey (EPN)', 'info@epn.ne', 'universite', 'Niger', '', 'a_envoyer'),
  ('ESCAE', 'info@escaegroup.org', 'universite', 'Niger', 'Akesse Akpro Victor', 'a_envoyer'),
  ('UPEN — Université Privée l''Élite de Niamey', 'upen@upenniger.com', 'universite', 'Niger', '', 'a_envoyer'),
  ('Swiss UMEF University of Niger', 'niamey@umefuni-afrique.swiss', 'universite', 'Niger', 'I. A. Tahirou Korambeizé', 'a_envoyer'),
  ('ESAE', 'scolarite@esae.bj', 'universite', 'Bénin', 'Clément Adéoti Adéchian', 'a_envoyer'),
  ('ESGIS Bénin', 'esgis.benin@esgis.org', 'universite', 'Bénin', 'Marcel Macy Akakpo', 'a_envoyer'),
  ('HECM — Haute École de Commerce et de Management', 'contact@hecm-afrique.net', 'universite', 'Bénin', 'Dr Bonaventure Natondé Aké', 'a_envoyer'),
  ('UCAO-UUC (Cotonou)', 'contact@ucaobenin.org', 'universite', 'Bénin', 'Rév. Père Béterbanfo Modeste Somé', 'a_envoyer'),
  ('Pigier Bénin', 'contact@pigier-benin.com', 'universite', 'Bénin', 'Dr Henri Tafou', 'a_envoyer'),
  ('IRGIB-Africa University', 'contact@irgibafrica.university', 'universite', 'Bénin', 'Dr Virgile Ahyi', 'a_envoyer'),
  ('ISM Adonaï (Bénin)', 'ismadonai@ismadonai.net', 'universite', 'Bénin', 'Codjo Charles Kouphin', 'a_envoyer'),
  ('UCAO-UUT (Lomé)', 'contacts@ucao-uut.tg', 'universite', 'Togo', 'Rév. Père Anicet Tounwendsida Kaboré', 'a_envoyer'),
  ('ESGIS Togo', 'esgis.togo@esgis.org', 'universite', 'Togo', 'Marcel Macy Akakpo', 'a_envoyer'),
  ('IAEC', 'infos.iaec@iaectogo.com', 'universite', 'Togo', '', 'a_envoyer'),
  ('Lomé Business School', 'info@lomebs.com', 'universite', 'Togo', 'Fulgence Amani', 'a_envoyer'),
  ('ISM Adonaï Togo', 'ismadonaitg@ismadonai.net', 'universite', 'Togo', 'Codjo Charles Kouphin', 'a_envoyer'),
  ('ESIG Global Success', 'contact@esig.tg', 'universite', 'Togo', 'Ambroise Toglo', 'a_envoyer'),
  ('Institut Polytechnique DEFITECH', 'defitechtogo@defitech.net', 'universite', 'Togo', 'Kossi Joachim Amouzou', 'a_envoyer'),
  ('USTTG — Université des Sciences et Technologies du Togo', 'usttg@yahoo.fr', 'universite', 'Togo', 'Pr Dieudonné Gumedzoé', 'a_envoyer'),
  ('Université Nongo Conakry (UNC)', 'contact@unc-edu.org', 'universite', 'Guinée', 'Mamadou Cellou Souaré', 'a_envoyer'),
  ('Université Mercure International (UMI)', 'contact@umi-gn.com', 'universite', 'Guinée', 'Mariane Diallo Tounkara', 'a_envoyer'),
  ('Université Internationale de Guinée (UIUG)', 'contact@uniguinee.com', 'universite', 'Guinée', '', 'a_envoyer'),
  ('Université Mahatma Gandhi de Guinée', 'contact@univmgandhiguinee.com', 'universite', 'Guinée', 'Mamadou Mouctar Savané', 'a_envoyer'),
  ('Université Ahmadou Dieng', 'contact@univadieng.org', 'universite', 'Guinée', 'Hadja Ramatoulaye Sow', 'a_envoyer'),
  ('Université Roi Mohammed VI (Guinée)', 'info@univ-roimohammed6.com', 'universite', 'Guinée', 'Pr Alexandre Lucien Richard', 'a_envoyer'),
  ('Université Aguibou Barry', 'contact@univ-uab.com', 'universite', 'Guinée', 'Néné Houdia Baldé (Barry)', 'a_envoyer'),
  ('LIU — Université Libanaise Internationale (Mauritanie)', 'info@liu.mr', 'universite', 'Mauritanie', 'Abderrahim Mourad', 'a_envoyer'),
  ('Sup''Management Mauritanie', 'supmgtmauritanie@supmanagement.ma', 'universite', 'Mauritanie', 'Mohamed Radhi Ould Mohamed El Hacen', 'a_envoyer'),
  ('GEU L''Académie', 'muriel.limam@geuacademie.com', 'universite', 'Mauritanie', 'Muriel Limam', 'a_envoyer'),
  ('ESIG Groupe', 'infoline@esiggroupe.com', 'universite', 'Mauritanie', 'Saliou Damien', 'a_envoyer'),
  ('Université Internationale de Libreville (UIL)', 'contact@uil-universite.com', 'universite', 'Gabon', 'Pr Jacques François Mavoungou', 'a_envoyer'),
  ('EM-Gabon Université', 'contact@em-gabon.com', 'universite', 'Gabon', 'Pr Daniel Franck Idiata', 'a_envoyer'),
  ('BGFI Business School (BBS)', 'contact-bbs@bgfi.com', 'universite', 'Gabon', 'Pr Pamphile Mezui Mbeng', 'a_envoyer'),
  ('ESGIS Gabon', 'esgis.gabon@esgis.org', 'universite', 'Gabon', 'Marcel Akakpo', 'a_envoyer'),
  ('African University of Management (AUM Gabon)', 'contact@aumgroupga.com', 'universite', 'Gabon', 'Esnel Iyembiyt', 'a_envoyer'),
  ('SupDeCom Gabon', 'contact@supdecom-gabon.com', 'universite', 'Gabon', 'Pr Fabien Okoue Metogo', 'a_envoyer'),
  ('ESGAE', 'esgae@esgae.org', 'universite', 'Congo-Brazzaville', 'Pr Roger Armand Makany', 'a_envoyer'),
  ('Université Libre du Congo (ULC)', 'universitelibre4@gmail.com', 'universite', 'Congo-Brazzaville', 'Pr Fidèle Mialoundama', 'a_envoyer'),
  ('Université Catholique du Congo-Brazzaville (UCCB)', 'info@uccbz.net', 'universite', 'Congo-Brazzaville', 'Abbé Olivier Massamba-Loubelo', 'a_envoyer'),
  ('EST-Littoral (Pointe-Noire)', 'est-littoral2000@gmail.com', 'universite', 'Congo-Brazzaville', 'Delphin Loembé', 'a_envoyer'),
  ('ASMT — African School of Management and Technology', 'contact@ecole-asmt.com', 'universite', 'Congo-Brazzaville', '', 'a_envoyer'),
  ('Université des Montagnes (UdM)', 'info@udm.aed-cm.org', 'universite', 'Cameroun', 'Pr Jeanne Ngogang', 'a_envoyer'),
  ('UCAC — Université Catholique d''Afrique Centrale', 'communication@ucac-icy.net', 'universite', 'Cameroun', 'Rév. Père Pr Thomas Bienvenu Tchoungui', 'a_envoyer'),
  ('IUC — Institut Universitaire de la Côte', 'iuc@myiuc.com', 'universite', 'Cameroun', 'Paul Guimezap', 'a_envoyer'),
  ('IUEs/INSAM', 'info@iues-univ.com', 'universite', 'Cameroun', '', 'a_envoyer'),
  ('UPAC — Université Protestante d''Afrique Centrale', 'rectorat@upac.cm', 'universite', 'Cameroun', 'Rév. Pr Samuel Frouisou', 'a_envoyer'),
  ('Institut Universitaire Siantou', 'siantou.univ@gmail.com', 'universite', 'Cameroun', 'Lucien Wantou Siantou', 'a_envoyer'),
  ('The ICT University', 'admin@ictuniversity.edu.cm', 'universite', 'Cameroun', 'Pr Victor Mbarika', 'a_envoyer'),
  ('CUIB — Catholic University Institute of Buea', 'info@cuib-cameroon.net', 'universite', 'Cameroun', 'Father George Nkeze', 'a_envoyer'),
  ('Saint Monica University', 'info@stmonicauniv.org', 'universite', 'Cameroun', 'Pr Januarius Jingwa Asongu', 'a_envoyer'),
  ('Fomic Polytechnic University Institute', 'info@fpu.cm', 'universite', 'Cameroun', 'Fossung Michael Forzeh', 'a_envoyer'),
  ('Université Adventiste Cosendai', 'contact@uacosendai-edu.net', 'universite', 'Cameroun', 'Aristide Tout Saint Nguelé', 'a_envoyer'),
  ('Institut Universitaire J. Ndi Samba', 'contact@universitendisamba.com', 'universite', 'Cameroun', 'Raymond Samba Ndi', 'a_envoyer'),
  ('Université HEC-Tchad', 'info@hec-tchad.org', 'universite', 'Tchad', 'Dr Ali Abdel-Rhamane Haggar', 'a_envoyer'),
  ('Université Emi Koussi (UNEK)', 'info@universiteemikoussi.com', 'universite', 'Tchad', 'Dr Allah-Ridy Koné', 'a_envoyer'),
  ('Université Roi Fayçal (URF)', 'inscriptions@urf.td', 'universite', 'Tchad', 'Pr Abdallah Bakhit Saleh', 'a_envoyer'),
  ('Sup''Management Tchad', 'infos@supmanagementchad.com', 'universite', 'Tchad', 'Mahamat Mbodou Mbodoumi', 'a_envoyer'),
  ('ISCAM', 'admission@iscam.mg', 'universite', 'Madagascar', 'Jaona Ranaivoson', 'a_envoyer'),
  ('Université Catholique de Madagascar (UCM)', 'ucm@ucm.mg', 'universite', 'Madagascar', 'Père Marc Ravelonantoandro', 'a_envoyer'),
  ('ISPM — Institut Supérieur Polytechnique de Madagascar', 'contact@ispm.education', 'universite', 'Madagascar', 'Pr Raboanary Julien Amédée', 'a_envoyer'),
  ('ESSCA — École Supérieure Sacré-Cœur Antanimena', 'contact@essca.mg', 'universite', 'Madagascar', 'Frère Andriambahoaka Omar Génao Patrick', 'a_envoyer'),
  ('Université Adventiste Zurcher (UAZ)', 'registraoffice@zurcher.edu.mg', 'universite', 'Madagascar', 'Dr Daniel Ismael Kancel', 'a_envoyer'),
  ('ESGNT — École Supérieure de Gestion et des Nouvelles Technologies', 'infos@esgnt.net', 'universite', 'RCA', 'Bertrand Rodolphe Mbeya Senam', 'a_envoyer'),
  ('CPUB — Complexe Polytechnique et Universitaire de Bangui', 'info@cpub-rca.com', 'universite', 'RCA', '', 'a_envoyer'),
  ('Hadina RIMTIC', 'contact@hadinarimtic.com', 'partenaire', 'Mauritanie', 'Zeinebou Abdeljelil', 'a_envoyer'),
  ('CTIC Dakar', 'contact@cticdakar.com', 'partenaire', 'Sénégal', 'Isidore Mbodji', 'a_envoyer'),
  ('Jokkolabs Dakar', 'hellodakar@jokkolabs.net', 'partenaire', 'Sénégal', 'Karim Sy', 'a_envoyer'),
  ('Consortium Jeunesse Sénégal (CJS)', 'contact@consortiumjeunessesenegal.org', 'partenaire', 'Sénégal', '', 'a_envoyer'),
  ('3FPT — Fonds de Financement de la Formation Professionnelle et Technique', 'contact@3fpt.sn', 'partenaire', 'Sénégal', 'Souleye Kane', 'a_envoyer'),
  ('DER/FJ — Délégation générale à l''Entrepreneuriat Rapide des Femmes et des Jeunes', 'contact@der.sn', 'partenaire', 'Sénégal', 'Dr Abdoulaye Niane', 'a_envoyer'),
  ('Chariow', 'support@chariow.com', 'partenaire', 'Bénin', 'Elias Mahugnon Missihoun', 'a_envoyer'),
  ('Fondation Sonatel', 'fondationsonatel@orange-sonatel.com', 'partenaire', 'Sénégal', 'Coura Sow', 'a_envoyer'),
  ('DoniLab', 'contact@donilab.net', 'partenaire', 'Mali', 'Dr Tidiane Ball', 'a_envoyer'),
  ('La Fabrique', 'contact@lafabrique-bf.com', 'partenaire', 'Burkina Faso', 'Lisa Tietiembou Barutel', 'a_envoyer'),
  ('CIPMEN — Centre Incubateur des PME du Niger', 'contact@cipmen.org', 'partenaire', 'Niger', 'Bello Mahamadou', 'a_envoyer'),
  ('ActivSpaces', 'info@activspaces.com', 'partenaire', 'Cameroun', 'Steve Tchoumba', 'a_envoyer'),
  ('Investir au Pays', 'contact@investiraupays.com', 'partenaire', 'Cameroun / diaspora', 'Philippe Simo', 'a_envoyer'),
  ('AppsTech', 'renonchong@appstech.com', 'partenaire', 'Cameroun', 'Rebecca Enonchong', 'a_envoyer'),
  ('MINJEC — Ministère de la Jeunesse et de l''Éducation Civique', 'courier@minjec.gov.cm', 'partenaire', 'Cameroun', 'Mounouna Foutsou', 'a_envoyer'),
  ('CNJC — Conseil National de la Jeunesse du Cameroun', 'contact@cnjcnyc.info', 'partenaire', 'Cameroun', 'Fadimatou Iyawa Ousmanou', 'a_envoyer');
